### PR TITLE
Change in header section (new modified styles)

### PR DESCRIPTION
**Pull request by amritpandey23**

### CODE REVIEW

**Comment by amritpandey23** [comment]
Please review and merge

**Review by ry4-n — CHANGES_REQUESTED** [review]
There's a lot of new styles in the production branch but there aren't any in the SASS files.  Additionally, i think there needs to be further discussion about content changes on the site.

**Comment by amritpandey23** [comment]
Alright I did'nt knew that we were using SASS! I will put changes in SASS files in future.

**Comment by Rayhatron** [comment]
We have stopped changes to the production site until the rework of the whole site in angular is finished. if you want to change something, it has to be in the rework branch.

**Pull request closed without merging**
